# permissions for end users to view customdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: imagedeployment
    app.kubernetes.io/part-of: imagedeployment
    app.kubernetes.io/managed-by: kustomize
  name: customdeployment-viewer-role
rules:
- apiGroups:
  - mycustom.deployment.aas
  resources:
  - customdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mycustom.deployment.aas
  resources:
  - customdeployments/status
  verbs:
  - get
